config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "lotteries#index"
  resources :lotteries, only: [:new, :index, :create, :edit, :destroy, :update]
  resources :results, only: [:new, :create, :destroy]
  resources :listeners, only: [:index, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  
  belongs_to :rarity
  has_many :results
end

app/models/listener.rb
class Listener < ApplicationRecord
  validates :name, presence: true

  has_many :results, dependent: :delete_all
end

app/models/lottery.rb
class Lottery < ApplicationRecord
  validates :name, presence: true

  has_many :rarities, dependent: :delete_all
  has_many :results

  def self.items?(lottery)
    items = []
    lottery.rarities.map {|rarity| items << rarity.items }
    result = items.flatten.present? ? true : false
    return result
  end
end

app/models/rarity.rb
class Rarity < ApplicationRecord
  validates :name, presence: true
  validates :weight, presence: true

  belongs_to :lottery, optional: true
  has_many :items, dependent: :delete_all

end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :lottery
  belongs_to :listener
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listeners_controller.rb
class ListenersController < ApplicationController
  def index
    @listeners = Listener.all
    @listener = Listener.new
  end

  def create
    @listener = Listener.new(name: params[:listener][:name])
    @listener.save
    redirect_to listeners_path
  end

  def destroy
    @listener = Listener.find(params[:id])
    @listener.destroy
    redirect_to listeners_path
  end
end

app/controllers/lotteries_controller.rb
class LotteriesController < ApplicationController

  before_action :find_lottery, only: [:edit, :destroy, :update]

  def new
    @lottery = Lottery.new
    @rarity = Rarity.new
  end

  def create
    @lottery = Lottery.new(lottery_params)
    rarities = []
    ActiveRecord::Base.transaction do
      @lottery.save
      lottery_id = @lottery.id
      params[:lottery][:rarities].each do |rarity_param|
        rarity = Rarity.new(rarity_params(rarity_param, lottery_id))
        rarities << rarity if rarity.name.present? && rarity.weight.present?
      end
      rarity_weight_check(rarities)
      Rarity.import rarities
    end
    redirect_to lotteries_path
  rescue
    redirect_to new_lottery_path
  end

  def index
    @lotteries = Lottery.all
  end
  
  def edit
    @rarities = Rarity.where(lottery: @lottery)
    @item = Item.new
    @items = Item.where(rarity_id: @rarities.ids)
    @form_length = 0
    @rarities.each {|r| @form_length += r.items.length }
    @form_length = @form_length > 3 ? @form_length : 3
    @rarity_names = @rarities.pluck(:name)
  end

  def update
    items = []
    ActiveRecord::Base.transaction do
      # ここにlotteryのupdateも追加する
      if params[:lottery][:items].present?
        params[:lottery][:items].each do |item_param|
          item = Item.new(name: item_param[:name], rarity_id: item_param[:rarity_id])
          items << item if item.name.present?
        end
      end
      if params[:lottery][:current_items].present?
        params[:lottery][:current_items].each do |current_item_param|
          item = Item.new(id: current_item_param[0], name: current_item_param[1][:name], rarity_id: current_item_param[1][:rarity_id])
          items << item if item.name.present?
        end
      end
      Item.import items, on_duplicate_key_update: [:name, :rarity_id]
    end
    redirect_to lotteries_path
  rescue
    redirect_to edit_lottery_path(@lottery.id)
  end

  def destroy
    ActiveRecord::Base.transaction do
      Result.where(lottery: @lottery).delete_all
      Item.where(rarity: @lottery.rarities).delete_all
      Rarity.where(lottery: @lottery).delete_all
      @lottery.destroy
      redirect_to lotteries_path
    end
  rescue
    render "index"
  end

  private

  def lottery_params
    params.require(:lottery).permit(:name)
  end

  def rarity_params(param, lottery_id)
    param.permit(:name, :weight).merge(lottery_id: lottery_id)
  end

  def find_lottery
    @lottery = Lottery.find(params[:id])
  end

  def rarity_weight_check(rarities)
    total_weight = 0
    rarities.each {|rarity| total_weight += rarity.weight }
    raise StandardError if total_weight != 100
  end

end

app/controllers/results_controller.rb
class ResultsController < ApplicationController

  def new
    @listeners = Listener.all
    @listener = params[:listener_id] ? Listener.find(params[:listener_id]) : @listeners.first
    @lottery = Lottery.find(params[:lottery_id])
    @rarities = Rarity.where(lottery_id: @lottery.id)
    @items = Item.where(rarity_id: @rarities.ids)
    @result = Result.new
    @results = Result.includes(:listener, :item).where(listener: @listener, lottery: @lottery).limit(1000)
  end

  def create
    lottery = Lottery.find(params[:result][:lottery_id])
    listener = Listener.find(params[:result][:listener_id])
    result_times = params[:result][:time].try(:to_i)

    result_list = []
    item_results(lottery, result_times).each do |item|
      result_list << Result.new(listener: listener, lottery: lottery, item: item)
    end
    Result.import result_list

    redirect_to new_result_path(lottery_id: lottery.id, listener_id: listener.id)
  end

  def destroy
    lottery = Lottery.find(params[:id])
    listener = Listener.find(params[:listener_id])
    Result.where(lottery: lottery, listener: listener).delete_all
    redirect_to new_result_path(lottery_id: lottery.id, listener_id: listener.id)
  end

  private

  def item_results(lottery, lottery_times)
    lottery_results = []
    lottery_inside = []
    lottery.rarities.each do |rarity|
      rarity_weight = rarity.weight
      rarity_weight.times {|i| lottery_inside << rarity }
    end

    rarity_results = []
    lottery_times.times {|i| rarity_results << lottery_inside.sample }
    rarity_results.each {|rarity| lottery_results << rarity.items.sample }
    lottery_results
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lottery_helper.rb
module LotteryHelper

  def rarity_names
    ["UR", "SSR", "SR", "R", "N"]
  end

  def rarities_forms
    
  end

end

app/helpers/result_helper.rb
module ResultHelper

  def rarity_weight(item)
    (item.rarity.weight.to_f / item.rarity.items.length.to_f).round(2)
  end

end

app/views/layouts/_header.html.erb
<div class="header">
  <div class="header-left header-items">
    <%= link_to root_path do %>
      <p><span class="header-item">うじゅガチャ</span></p>
    <% end %>
  </div>
  <div class="header-right header-items">
    <%= link_to "ガチャを作る", new_lottery_path, class: "header-item" %>
    <%= link_to "リスナーを登録する", listeners_path, class: "header-item" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ujugacha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/listeners/index.html.erb
<div class="container">
  <%= form_with model: @listener, class: "listener-form", local: true do |f| %>
    <%= f.label :name, "リスナー名" %>
    <%= f.text_field :name %>
    <%= f.submit "登録" %>
  <% end %>

  <% @listeners.each do |listener| %>
    <div>
      <%= listener.name %>
      <%= link_to "削除", listener_path(listener.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/lotteries/edit.html.erb
<div class="container">
  <%= form_with model: @lottery, class: "lottery-items-form", local: true do |f| %>
    <h3><%= @lottery.name %>の編集画面</h3>
    <% if @items.blank? %>
      <% @rarities.each do |rarity| %>
        <div class="item">
          <%= f.fields_for "items[]", @item do |i| %>
            <i class="fa-solid fa-trash-can delete-item"></i>
            <%= i.label :name, "アイテムの名前" %>
            <%= i.text_field :name %>
            <%= i.label :rarity_id, "レアリティ設定" %>
            <%= i.select :rarity_id, options_for_select(@rarities.map {|r| [r.name, r.id, {}]}, rarity.id), {}, {class: "rarity-select"} %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <% @items.each do |item| %>
        <div class="item">
          <%= f.fields_for "current_items[]", item do |i| %>
            <i class="fa-solid fa-trash-can delete-item"></i>
            <%= i.label :name, "アイテムの名前" %>
            <%= i.text_field :name, value: item.name %>
            <%= i.label :rarity_id, "レアリティ設定" %>
            <%= i.select :rarity_id, options_for_select(@rarities.map {|r| [r.name, r.id, {}]}, item.rarity_id), {}, {class: "rarity-select"} %>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <%= button_tag "アイテムの追加+", type: "button", class: "btn-primary", id: "add-item" %>
    <p id="value-presence-alert" >※空欄のアイテム名があると登録出来ません</p>
    <p id="item-presence-alert" >※各レアリティ ひとつ以上のアイテム登録が必要です</p>
    <div>
      <%= f.submit "登録", class: "items-submit" %>
    </div>
  <% end %>
</div>
<div id="hidden-rarity" data-rarity="<%= @rarity_names %>"></div>
<script>
$(function(){
  let index;
  let raritySelects;
  let rarirtyLength;
  let rarityCheck;
  const raritiesOrigin = $("#hidden-rarity").data().rarity;
  const trashBtn = $("<i class='fa-solid fa-trash-can delete-item'></i>");

  validateCheck(presenceRarityCheck(), presenceValueCheck());

  $(document).on("keyup", "input[type=text]", function(){
    validateCheck(presenceRarityCheck(), presenceValueCheck());
  })

  function validateCheck(r, v){
    if(r == true && v == true){
      $("input[type=submit]").attr("disabled", false);
    } else {
      $("input[type=submit]").attr("disabled", "disabled");
    }
  };

  $(document).on("change", ".rarity-select", function(){
    validateCheck(presenceRarityCheck(), presenceValueCheck() );
  });

  $(document).on("click", "#add-item", function(){
    $this = $(this);
    $form = $this.prev();
    $new_form = $form.clone();
    $new_form.find("input").val("");
    $this.before($new_form);
    $trashBtn = $(".delete-item");
    if ($trashBtn.length == 0){
      $(".item").prepend(trashBtn);
    }
    validateCheck(presenceRarityCheck(), presenceValueCheck() );
  });

  $(document).on("click", ".delete-item", function(){
    $this = $(this);
    $form = $this.parent();
    $form.remove();
    validateCheck(presenceRarityCheck(), presenceValueCheck() );
    $trashBtn = $(".delete-item");
    if ($trashBtn.length == 1){
      $trashBtn.remove();
    }
  });

  function presenceRarityCheck() {
    var rarities = [...raritiesOrigin];
    raritySelects = $(".rarity-select");
    $.each(raritySelects, function(i, raritySelect){
      selectRarity = $(raritySelect).find("option:selected").text();
      if(rarities.includes(selectRarity)){
        var index = rarities.indexOf(selectRarity);
        rarities.splice(index, 1)
      }
    });
    rarityLength = rarities.length;
    if(rarityLength == 0){
      $("#item-presence-alert").hide();
      return true;
    } else {
      $("#item-presence-alert").show();
      return false;
    }
  };

  function presenceValueCheck(){
    var itemImputs = $("input[type=text]");
    var empValue = 0;
    itemImputs.each(function(i, input) {
       if ($(input).val() == "") empValue += 1;
    })
    if (empValue > 0){
      $("#value-presence-alert").show();
      return false;
    } else {
      $("#value-presence-alert").hide();
      return true;
    }
  };
})
</script>

app/views/lotteries/index.html.erb
<div class="container">
  <h1>うじゅガチャ作るよ</h1>
  <div class="row">
    <% @lotteries.each do |lottery| %>
      <div class="col-12 lottery">
        <div class="col-2 lottery-left">
          <%= image_tag "gacha.png", class: "gacha-image" %>
        </div>
        <div class="col-10 lottery-right">
          <h2 class="lottery-title">
            <%= lottery.name %>
          </h2>
          <div class="lottery-options">
            <% if !Lottery.items?(lottery) %>
              <%= link_to edit_lottery_path(lottery.id), class: "option-link" do %>
                <p class="lottery-option"><i class="fa-solid fa-wrench fa-lg"></i><span class="hover-word">アイテム登録</span></p>
              <% end %>
            <% else %>
              <% if Listener.last.present? %>
                <%= link_to new_result_path(lottery_id: lottery.id), class: "option-link" do %>  
                  <p class="lottery-option"><i class="fa-solid fa-gem fa-lg"></i><span class="hover-word">ガチャを回す</span></p>
                <% end %>
              <% end %>
            <% end %>
            <%= link_to lottery_path(lottery.id), class: "lottery-delete option-link", method: :delete  do %>
              <p class="lottery-option"><i class="fa-solid fa-trash-can fa-lg"></i><span class="hover-word">ガチャを削除</span></p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<style>
.gacha-image {
  width: 100px;
}

.container {
  padding-top: 24px;
}

.lottery {
  display: flex;
  border-top: 1px solid #f4deff;
  padding: 12px 0;
}

.lottery-right {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
}

.lottery-title {
  font-size: 32px;
}

.lottery-options {
  display: flex;
  justify-content: end;
}

.lottery-delete {
  margin-left: 8px;
}

.hover-word {
  display: none;
  transition: 0.5s ease;
  font-size: 16px;
}

.lottery-option .hover-word {
  display: inline;
  color: #fff;
}

.option-link {
  padding: 3px;
  border-radius: 3px;
  color: #fff;
  background: #874bb8;
  text-decoration: none !important;
}

</style>

app/views/lotteries/new.html.erb
<div class="container">
  <h1>ガチャを作る画面</h1>

  <%= form_with model: @lottery, class: "lottery-form", local: true do |f| %>
    <%= f.label :name, "ガチャの名前" %>
    <%= f.text_field :name %>
    <br>
    <% 5.times do |i| %>
      <%= f.fields_for "rarities[]", @rarity do |r| %>
        <div class="rarity">
          <i class="fa-solid fa-trash-can delete-rarity"></i>
          <%= r.label :name, "レアリティの名前" %>
          <%= r.text_field :name %>
          <%= r.label :weight, "確率" %>
          <%= r.number_field :weight, class: "weight" %>
        </div>
      <% end %>
    <% end %>
    <%= button_tag "レアリティの追加+", type: "button", class: "btn-primary", id: "add-rarity" %>
    <p>合計確率<span id="sum-weight">0</span></p>
    <p id="sum-weight-alert" >※レアリティの合計確率が100%にならないと登録できません（仮）</p>
    <%= f.submit "登録" %>
  <% end %>
</div>

<script>
$(function(){
  let weights = $(".weight");
  let weightNums;
  let num;
  let sumWeight = 0;
  let sumWeightText;
  const trashBtn = $("<i class='fa-solid fa-trash-can delete-rarity'></i>");

  sumWeightHandred();
  isNumJustHandred();

  $(document).on("click", "#add-rarity", function(){
    $this = $(this);
    $form = $this.prev();
    $new_form = $form.clone();
    $new_form.find("input").val("");
    $this.before($new_form);
    $trashBtn = $(".delete-rarity");
    if ($trashBtn.length == 0){
      $(".rarity").prepend(trashBtn);
    }
  });

  $(document).on("click", ".delete-rarity", function(){
    $this = $(this);
    $form = $this.parent();
    $form.remove();
    sumWeightHandred();
    isNumJustHandred();
    $trashBtn = $(".delete-rarity");
    if ($trashBtn.length == 1){
      $trashBtn.remove();
    }
  });

  $(document).on("change keyup", ".weight", function(){
    sumWeightHandred();
    isNumJustHandred();
  });

  function sumWeightHandred(){
    sumWeight = 0;
    weights = $(".weight");
    weights.each(function(i, weight){
      num = Number($(weight).val());
      sumWeight += num;
    });
    $("#sum-weight").text(sumWeight);
  };

  function isNumJustHandred(){
    sumWeightText = $("#sum-weight").html();
    if(Number(sumWeightText) != 100){
      $("#sum-weight-alert").show();
      $("input[type=submit]").attr("disabled", "disabled");
    } else {
      $("#sum-weight-alert").hide();
      $("input[type=submit]").attr("disabled", false);
    }
  };

})
</script>

app/views/results/new.html.erb
<div class="container">
  <%= @lottery.name %>
  <div>
    <%= form_with model: @result, lodal: true do |f|%>
      <%= f.label :listener_id, "ガチャを引くリスナー" %>
      <br>
      <%= f.select :listener_id, options_for_select(@listeners.map {|listener| [listener.name, listener.id, {}]}, @listener.id), {}, {class: "listener-select"} %>
      <div>
        <%= f.number_field :time, value: 1, in: 1..100 %>
        回
        <%= f.submit "ガチャる" %>
        <%= f.hidden_field :lottery_id, value: @lottery.id%>
      </div>
    <% end %>
  </div>
  <div class="row">
    <div class="col-6">
      <h2><%= @lottery.name %></h2>
      <h3>アイテム一覧</h3>
      <% @items.each do |item| %>
        <div class="row result-left">
          <span class="col-4"><%= item.name %></span>
          <span class="col-2"><%= item.rarity.name %></span>
          <span class="col-6 text-right"><%= rarity_weight(item) %>%</span>
        </div>
      <% end %>
    </div>
    <div class="col-6">
      <div class="result-history">
        <h2>ガチャ履歴</h2>
        <%= link_to "履歴を削除", result_path(@lottery.id, listener_id: @listener.id), method: :delete %>
      </div>
      <div class="result-box">
        <% @results.each do |result| %>
          <div class="row">
            <span class="col-4"><%= result.created_at.strftime("%Y/%-m/%-d %-H:%-M:%-S") %></span>
            <span class="col-8"><%= @listener.name %>さんが<%= result.item.name %>[<%= result.item.rarity.name %>]を獲得しました</span>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
$(function(){
  $(document).on("change", ".listener-select", function(){
    console.log(this);
    window.location.href = "/results/new?lottery_id=<%= @lottery.id %>&listener_id="+`${$(this).val()}`;
  });
})
</script>

<style>
.result-box {
  max-height: 800px;
  overflow: scroll;
  background: #ddd;
  margin-bottom: 30px;
}

.text-right {
  text-align: right;
}

.result-left {
  width: 400px;
}

.result-history {
  display: flex;
  justify-content: space-between;
}
</style>